"""create device_profiles table

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-25 21:48:15.106532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '0001'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mount_hint', sa.String(), nullable=True),
    sa.Column('codec', sa.String(), nullable=False),
    sa.Column('container', sa.String(), nullable=False),
    sa.Column('max_bitrate', sa.Integer(), nullable=False),
    sa.Column('min_bitrate', sa.Integer(), nullable=False),
    sa.Column('bitrate_step', sa.Integer(), nullable=False),
    sa.Column('max_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sample_rate_max', sa.Integer(), nullable=False),
    sa.Column('m3u_path_style', sa.String(), nullable=False),
    sa.Column('folder_layout', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_profiles')
    # ### end Alembic commands ###
