"""create features table

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-26 20:36:40.513036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '0002'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('scale', sa.String(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('mood_happy', sa.Float(), nullable=True),
    sa.Column('mood_sad', sa.Float(), nullable=True),
    sa.Column('mood_aggressive', sa.Float(), nullable=True),
    sa.Column('mood_relaxed', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('spectral_centroid', sa.Float(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    # ### end Alembic commands ###
